# List of tokens to track
tokens:
  - symbol: WETH
    address: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'
  - symbol: USDC
    address: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48'
  - symbol: DAI
    address: '0x6B175474E89094C44Da98b954EedeAC495271d0F'
  - symbol: WBTC
    address: '0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599'

# List of DEXes to monitor
dexes:
  - Uniswap V2
  - Sushiswap
  - Balancer

# 1inch API configuration
api:
  base_url: 'https://api.1inch.io/v5.0'
  chain_id: 1  # Ethereum mainnet